import { Inter } from 'next/font/google'
import '../globals.css'
import { userDataManager } from "@/Config/userManager";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Prar Labs',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  userDataManager.set("text-multiplier",1)
  return (
      <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
